version: 2
jobs:
  shellcheck:
    docker:
      - image: koalaman/shellcheck-alpine:stable
    steps:
      - checkout
      - run:
          name: スクリプトのチェック
          command: |
            find . -type f -name '*.sh' | wc -l
            find . -type f -name '*.sh' | xargs shellcheck --external-sources
  start-instance:
    docker:
      - image: koalaman/shellcheck-alpine:stable
    steps:
      - checkout
      - run:
          name: インスタンスの開始
          command: |
            curl https://1neuyud4aj.execute-api.us-east-1.amazonaws.com/prod/us-east-1/i-0dd1c8675f4c06f43

workflows:
  version: 2
  workflow:
    jobs:
      - shellcheck
      - start-instance:
          requires:
            - shellcheck
          filters:
            branches:
              only: master